name: 'Install VapourSynth'
description: 'Install VapourSynth on the current runner'
icon: arrow-down-circle
color: blue

inputs:
  version:
    description: 'The version to install'
    required: true
    default: 'latest'
  cache:
    description: 'Cache the compilation'
    required: false
    default: true
outputs:
  version:
    description: 'Contains the actually installed version'
runs:
  using: 'node12'
  main: 'dist/install.js'
